apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-cart-postgres
  namespace: smart-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-cart-postgres
  template:
    metadata:
      labels:
        app: smart-cart-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_DB
          value: smartcart
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-cart-secrets
              key: DATABASE_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: smart-cart-postgres
  namespace: smart-cart
spec:
  selector:
    app: smart-cart-postgres
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: smart-cart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 